### ISSUE TITLE
Don't match 10bit as episode 10

### ISSUE THREAD

**Issue by rcombs** [soruly/aniep#34]
From answer.txt:
```
10	(110729) 夢喰い－つるみく式ゲーム製作－ 樟葉瑠美 調教編 (DVD 1280x720 x264 10bit AAC).mp4
```
There are at least a few entries like this. I'd expect the best solution would be to just remove "10bit", as with "x264" and "x265" here: https://github.com/soruly/aniep/blob/51954d47d5c35304931fa3ce9c482ca233e0059b/src/index.js#L7

**Comment by soruly** [comment]
Good idea.
Resolved in aae25aa8f6b89e9726392ed56775a658df1a75cf
